ÖDEV-SON-enson/ödevv/Areas/Admin/Controllers/RolyonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ödevv.Areas.Admin.Models;
using ödevv.Models;

namespace ödevv.Areas.Admin.Controllers
{
    public class RolyonetimController : Controller
    {

        ApplicationDbContext context =new ApplicationDbContext();
        // GET: Admin/Rolyonetim
        public ActionResult Index()
        {

            var roleStore = new RoleStore<IdentityRole>();
            var roleManager =new RoleManager<IdentityRole>(roleStore);

            var model =roleManager.Roles.ToList();
           
            return View(model);
        }

        public ActionResult Rolekle()
        {


            return View("");
 }

        [HttpPost]
        public ActionResult Rolekle(RolEkleModel rol)
        {

            var roleStore = new RoleStore<IdentityRole>();
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            if (roleManager.RoleExists(rol.RolAd) == false)
            {
                roleManager.Create(new IdentityRole(rol.RolAd));

            }

            return RedirectToAction("Index");
        }

        public ActionResult RoleKullaniciEkle()
        {


            return View();
        }


        [HttpPost]
        public ActionResult RoleKullaniciEkle(RolEkleModel model)
        {

            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore =new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var kullanici = userManager.FindByName(model.KullaniciAdi);


          

            if (!userManager.IsInRole(kullanici.Id, model.RolAdi))
            {
                userManager.AddToRole(kullanici.Id, model.RolAdi);

            }

            return RedirectToAction("Index");
        }
    }
}

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Rolyonetim/Index.cshtml
@using ödevv.Areas.Admin.Controllers
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    Layout = null;
}

<ul>
    @foreach (var item in Model)
    {

        <li>@item.Name-@item.Users.Count</li>
    }

</ul>

@Html.ActionLink("Yeni rol ekle","Rolekle","Rolyonetim");

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Rolyonetim/RoleKullaniciEkle.cshtml
@model ödevv.Areas.Admin.Models.RolEkleModel



@using (Html.BeginForm("RoleKullaniciEkle", "Rolyonetim", FormMethod.Post))
{
    @Html.LabelFor(m => m.KullaniciAdi) @Html.TextBoxFor(m => m.KullaniciAdi)
    <br />
        @Html.LabelFor(m => m.RolAdi) @Html.TextBoxFor(m => m.RolAdi)
        <br />
        <input type="submit" />

}

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Rolyonetim/Rolekle.cshtml
@model ödevv.Areas.Admin.Models.RolEkleModel
@{
    Layout = null;
}

<h2>ROL EKLE</h2>

@using (Html.BeginForm("Rolekle","Rolyonetim",FormMethod.Post))
{
    @Html.TextBoxFor(m=>m.RolAd)
    <input type="submit"/>


}