ÖDEV-SON-enson/ödevv/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ödevv.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
       
        [Authorize]
        // GET: Admin/Home
        public ActionResult index()
        {
            return View();
        }


        public ActionResult login()
        {
            return View();
        }

        public ActionResult tables()
        {
            return View();
        }

        public ActionResult user()
        {
            return View();
        }
    }
}

ÖDEV-SON-enson/ödevv/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ödevv.Areas.Admin.Models;

namespace ödevv.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {

        castvalleyEntities db= new castvalleyEntities();

        // GET: Admin/Slider
        public ActionResult slider()

        {
            var model = db.slider.OrderByDescending(x => x.ID).ToList();

            return View(model);
        }

        public ActionResult add()
        {
            
            return View();

        }

        const string ResimYolu = "/Content/img/";

        public ActionResult addslider(slidermodel model)
        {

            string fileName = string.Empty;
            
            if (ModelState.IsValid)
            {
                
           
                //dosyaya kaydetme

                if (model.sliderfoto != null && model.sliderfoto.ContentLength > 0)
                {
                    fileName = model.sliderfoto.FileName;
                    var path=Path.Combine( Server.MapPath(ResimYolu)  ,fileName);
                    model.sliderfoto.SaveAs(path);

                }
                
                
                //ef nesnesi olusturma
                slider slider=new slider();
                slider.baslangictarihi = model.baslangictarihi;
                slider.bitistarihi = model.bitistarihi;
                slider.slidertext = model.slidertext;
                slider.imagepath = ResimYolu+fileName;



                db.slider.Add(slider);
                db.SaveChanges();
            }
            return RedirectToAction("slider");



        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
          var model= db.slider.Find(id);

            //db.slider.FirstOrderDefault(x=>x.ID==id)

            return View(model);

        }

        [HttpPost]
        public ActionResult Edit(slider model)
        {
            if(ModelState.IsValid)
            {
                

                var attached =db.slider.Attach(model);

                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            
             }    

           
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.slider.Find(id);

            //db.slider.FirstOrderDefault(x=>x.ID==id)

            return View(model);

        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.slider.Find(id);
            db.slider.Remove(model);
            db.SaveChanges();

            return RedirectToAction("slider");


        }
    }
}

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Slider/Delete.cshtml
@model ödevv.slider

@{
    Layout = null;
}

<h2>Delete</h2>

silmek istediğinize eminmisiniz?

<br/>

@Model.slidertext
<br/>
@Html.ActionLink("Kabul Ediyorum","DeleteConfirm",new{id=Model.ID})
<br/>
@Html.ActionLink("Kabul Etmiyorum","slider")

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Slider/Edit.cshtml
@model ödevv.slider

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>BLOCKS - Bootstrap Dashboard Theme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Carlos Alvarez - Alvarez.is">

    <link rel="stylesheet" type="text/css" href="/Areas/Admin/css/bootstrap.min.css" />

    <link href="/Areas/Admin/css/main.css" rel="stylesheet">
    <link href="/Areas/Admin/css/font-style.css" rel="stylesheet">
    <link href="/Areas/Admin/css/flexslider.css" rel="stylesheet">

    <script type="text/javascript" src="/Areas/Admin/js/jquery.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/Areas/Admin/js/lineandbars.js"></script>

    <script type="text/javascript" src="/Areas/Admin/js/dash-charts.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/gauge.js"></script>

    <!-- NOTY JAVASCRIPT -->
    <script type="text/javascript" src="/Areas/Admin/js/noty/jquery.noty.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/noty/layouts/top.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/noty/layouts/topLeft.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/noty/layouts/topRight.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/noty/layouts/topCenter.js"></script>

    <!-- You can add more layouts if you want -->
    <script type="text/javascript" src="/Areas/Admin/js/noty/themes/default.js"></script>
    <!-- <script type="text/javascript" src="assets/js/dash-noty.js"></script> This is a Noty bubble when you init the theme-->
    <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
    <script src="/Areas/Admin/js/jquery.flexslider.js" type="text/javascript"></script>

    <script type="text/javascript" src="/Areas/Admin/js/admin.js"></script>

    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Google Fonts call. Font Used Open Sans & Raleway -->
    <link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

    <script type="text/javascript">
    $(document).ready(function () {

        $("#btn-blog-next").click(function () {
            $('#blogCarousel').carousel('next')
        });
        $("#btn-blog-prev").click(function () {
            $('#blogCarousel').carousel('prev')
        });

        $("#btn-client-next").click(function () {
            $('#clientCarousel').carousel('next')
        });
        $("#btn-client-prev").click(function () {
            $('#clientCarousel').carousel('prev')
        });

    });

    $(window).load(function () {

        $('.flexslider').flexslider({
            animation: "slide",
            slideshow: true,
            start: function (slider) {
                $('body').removeClass('loading');
            }
        });
    });

    </script>
</head>

<div class="navbar-nav navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active">@Html.ActionLink("Ana Sayfa", "index", "AdminHome")</li>
                <li>@Html.ActionLink("Giriş", "login", "AdminHome")</li>
                <li>@Html.ActionLink("Tablolar", "tables", "AdminHome")</li>
                <li>@Html.ActionLink("Kullanıcı", "user", "AdminHome")</li>

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>slider</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.imagepath , htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.imagepath, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.imagepath, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.slidertext, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.slidertext, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.slidertext, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.baslangictarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.baslangictarihi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.baslangictarihi, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.bitistarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bitistarihi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.bitistarihi, "", new { @class = "text-danger" })
                </div>
            </div>
    
            
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Slider/add.cshtml
@model ödevv.Areas.Admin.Models.slidermodel

@{
    Layout = null;
}

<head>
    <meta charset="utf-8">
    <title>BLOCKS - Bootstrap Dashboard Theme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="stylesheet" type="text/css" href="/Areas/Admin/css/bootstrap.min.css" />

    <link href="/Areas/Admin/css/main.css" rel="stylesheet">
    <link href="/Areas/Admin/css/font-style.css" rel="stylesheet">
    <link href="/Areas/Admin/css/register.css" rel="stylesheet">

    <script type="text/javascript" src="/Areas/Admin/js/jquery.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/bootstrap.min.js"></script>

    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Google Fonts call. Font Used Open Sans & Raleway -->
    <link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
</head>

    <!-- NAVIGATION MENU -->

<div class="navbar-nav navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active">@Html.ActionLink("Ana Sayfa", "index", "AdminHome")</li>
                <li>@Html.ActionLink("Giriş", "login", "AdminHome")</li>
                <li>@Html.ActionLink("Tablolar", "tables", "AdminHome")</li>
                <li>@Html.ActionLink("Kullanıcı", "user", "AdminHome")</li>
             
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>





@using (Html.BeginForm("addslider","Slider",FormMethod.Post,new {@class="form-horizontal",enctype="multipart/form-data"}))
{

        <div class="col-sm-6 col-lg-6">
            <div id="register-wraper">
                <form id="register-form" class="form">
                    <legend>Slider Ekleme</legend>

                    <div class="body">
                        <!-- slider text-->

                        @Html.LabelFor(x=>x.slidertext)
                        @Html.TextBoxFor(x=>x.slidertext,new {@class= "input-huge", placeholder="slider yazısı" }  )
                        
                        <!-- baslangıc tarihi-->
                        @Html.LabelFor(x => x.baslangictarihi)
                        @Html.TextBoxFor(x => x.baslangictarihi, new { @class = "input-huge", placeholder = "Başlangıç Tarihi" })
                        @*bitiş tarihi *@

                        @Html.LabelFor(x => x.bitistarihi)
                        @Html.TextBoxFor(x => x.bitistarihi, new { @class = "input-huge", placeholder = "Bitiş Tarihi" })


                        @Html.LabelFor(x => x.sliderfoto)
                        @Html.TextBoxFor(x => x.sliderfoto, new { @class = "input-huge", placeholder = "Resim Yolu" ,type="file" })


                    </div>

                    <div class="footer">
                       
                        <button type="submit" class="btn btn-success">Ekle</button>
                    </div>
                </form>
            </div>
        </div>

   



}

ÖDEV-SON-enson/ödevv/Areas/Admin/Views/Slider/slider.cshtml
@model List<slider>

@{
    Layout = null;
}
<head>
    <meta charset="utf-8">
    <title>Slider Tablosu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="stylesheet" type="text/css" href="/Areas/Admin/css/bootstrap.min.css" />

    <!-- DATA TABLE CSS -->
    <link href="/Areas/Admin/css/table.css" rel="stylesheet">

    <script type="text/javascript" src="/Areas/Admin/js/jquery.js"></script>
    <script type="text/javascript" src="/Areas/Admin/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/Areas/Admin/js/admin.js"></script>

    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Google Fonts call. Font Used Open Sans -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

    <!-- DataTables Initialization -->
    <script type="text/javascript" src="/Areas/Admin/js/datatables/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#dt1').dataTable();
        });
    </script>


</head>

<div class="navbar-nav navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
       
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active">@Html.ActionLink("Ana Sayfa", "index", "AdminHome")</li>
                <li>@Html.ActionLink("Giriş", "login", "AdminHome")</li>
                <li>@Html.ActionLink("Tablolar", "tables", "AdminHome")</li>
                <li>@Html.ActionLink("Kullanıcı", "user", "AdminHome")</li>
              
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>


<div class="row">
    <div class="col-sm-12 col-lg-12">
        <h4><strong>Slider Tablosu</strong></h4>
        <table class="display">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Basşlangıç tarihi</th>
                    <th>Bitiş tarihi</th>
                    <th>Text</th>
                    <th>Resim yolu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>@item.ID</td>
                        <td>@item.baslangictarihi</td>
                        <td>@item.bitistarihi</td>
                        <td>@item.slidertext</td>
                        <td>@item.imagepath</td>
                       <td>@Html.ActionLink("Düzenle","Edit","Slider", new {id=item.ID }, null)|@Html.ActionLink("Sil","Delete","Slider", new { id = item.ID }, null) </td>
                    </tr>


                }




            </tbody>
        </table><!--/END First Table -->
        <br>
        <!--SECOND Table -->




    </div><!--/span12 -->
</div>